#!/bin/bash
# Independent-reference correctness test (the check behind PRs #4712/#4713). Reads Perl-reference
# word/hash pairs pre-generated by gen_vectors.sh (via WSL), then cracks them with each WIN-branch
# kernel. All cracked => the optimized kernel matches an implementation that never saw hashcat's code.
HC=/c/Users/jeff/Documents/hashcat
PV=/c/Users/jeff/Documents/autoresearch/pv
cd "$HC" || exit 1
for M in "$@"; do
  g="$PV/gen_$M.txt"; [ -s "$g" ] || { echo "m$M: no reference vectors"; continue; }
  git checkout -q "autoresearch/$M-jul6" 2>/dev/null || { echo "m$M: no win branch"; continue; }
  head=$(git rev-parse --short HEAD)
  awk -F"'" 'NF>=2{print $2}' "$g" > "$PV/h.txt"
  sed -E "s/^echo (.*) \| \.\/hashcat.*/\1/" "$g" | sed -E 's/ +$//' > "$PV/w.txt"
  n=$(grep -c . "$PV/h.txt")
  pad=$(printf 'm%05d' "$M"); rm -f kernels/${pad}_*.kernel 2>/dev/null; rm -f "$PV/out.txt"
  ./hashcat.exe -a 0 -m "$M" "$PV/h.txt" "$PV/w.txt" --potfile-disable -o "$PV/out.txt" \
    --quiet -d 1 -D 2 --self-test-disable >/dev/null 2>&1
  c=$(grep -c . "$PV/out.txt" 2>/dev/null || echo 0)
  echo "m$M ($head): cracked $c/$n Perl-reference hashes -> $([ "$c" -ge "$n" ] && echo 'PASS (kernel correct)' || echo "CHECK ($c/$n)")"
done
git checkout -q master 2>/dev/null
